// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:897c4226-55c3-4a08-829c-7f17d546ce37",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_cdnplLvVD",
    "aws_user_pools_web_client_id": "1lk2mv1sa8u429sv7kub3e2g88",
    "oauth": {},
    "aws_content_delivery_bucket": "quit-genius-test-20200223134139-hostingbucket-node",
    "aws_content_delivery_bucket_region": "eu-west-2",
    "aws_content_delivery_url": "http://quit-genius-test-20200223134139-hostingbucket-node.s3-website.eu-west-2.amazonaws.com"
};


export default awsmobile;
